highlighter: rouge
plugins:
  - jekyll-feed
name: Crsando's Blog
title: Crsando's Blog
description: Welcome to my blog
author: Crsando
permalink: /:year/:month/:day/:title:output_ext
url: https://crsando.github.io